spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tienda
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: desafio3cs
